CREATE TABLE VILLAGER
(
  ID                   NUMBER,
  ID_CARD              VARCHAR2(128 BYTE),
  VILLAGER_NAME        VARCHAR2(128 BYTE),
  VILLAGER_SEX         VARCHAR2(128 BYTE),
  VILLAGER_TELEPHONE   VARCHAR2(128 BYTE),
  VILLAGER_OMMENT      VARCHAR2(4000 BYTE),
  LAST_MODIFY_ACCOUNT  VARCHAR2(128 BYTE),
  LAST_MODIFY_TIME     TIMESTAMP(6),
  ENABLE               VARCHAR2(128 BYTE),
  BINDING_TO_ID        VARCHAR2(128 BYTE),
  CONSTRAINT VILLAGER_PK
 PRIMARY KEY
 (ID)
);


CREATE TABLE WELFARE_POLICY
(
  ID                         NUMBER,
  WELFARE_POLICY_NAME        VARCHAR2(512 BYTE),
  LAST_MODIFY_TIME           TIMESTAMP(6),
  LAST_MODIFY_ACCOUNT        VARCHAR2(128 BYTE),
  WELFARE_POLICY_START_TIME  TIMESTAMP(6),
  WELFARE_POLICY_END_TIME    TIMESTAMP(6),
  WELFARE_POLICY_COMMENT     VARCHAR2(1024 BYTE),
  WELFARE_POLICY_FOR_ALL     VARCHAR2(128 BYTE),
  CONSTRAINT WELFARE_POLICY_PK
 PRIMARY KEY
 (ID)
);


CREATE TABLE WELFARE_POLICY_DETAIL
(
  ID                      NUMBER,
  WELFARE_POLICY_ID       INTEGER,
  PRODUCT_ID              VARCHAR2(128 BYTE),
  PRODUCT_NAME            VARCHAR2(512 BYTE),
  PRODUCT_QUANTITY        INTEGER,
  PRODUCT_MEASURING_UNIT  VARCHAR2(128 BYTE),
  LAST_MODIFY_TIME        TIMESTAMP(6),
  LAST_MODIFY_ACCOUNT     VARCHAR2(128 BYTE),
  CONSTRAINT WELFARE_POLICY_DETAIL_PK
 PRIMARY KEY
 (ID)
);


CREATE TABLE VILLAGER_WELFARE
(
  ID                   NUMBER,
  VILLAGER_ID          VARCHAR2(128 BYTE),
  WELFARE_POLICY_ID    INTEGER,
  LAST_MODIFY_ACCOUNT  VARCHAR2(128 BYTE),
  LAST_MODIFY_TIME     TIMESTAMP(6),
  CONSTRAINT VILLAGER_WELFARE_PK
 PRIMARY KEY
 (ID)
);


CREATE TABLE VILLAGER_WELFARE_DRAW_DETAIL
(
  ID                        NUMBER,
  VILLAGER_WELFARE_DRAW_ID  NUMBER,
  VILLAGER_WELFARE_ID       NUMBER,
  PRODUCT_ID                VARCHAR2(128 BYTE),
  PRODUCT_NAME              VARCHAR2(128 BYTE),
  PRODUCT_QUANTITY          INTEGER,
  PRODUCT_MEASURING_UNIT    VARCHAR2(128 BYTE),
  LAST_MODIFY_TIME          TIMESTAMP(6),
  LAST_MODIFY_ACCOUT        VARCHAR2(128 BYTE),
  CONSTRAINT VILLAGER_WELFARE_DRAW_DETAILPK
 PRIMARY KEY
 (ID)
);


CREATE TABLE VILLAGER_WELFARE_DRAW
(
  ID                   NUMBER,
  VILLAGER_ID          VARCHAR2(128 BYTE),
  DRAW_TYPE            VARCHAR2(128 BYTE),
  PROXY_VILLAGER_ID    VARCHAR2(128 BYTE),
  PROXY_VILLAGER_NAME  VARCHAR2(128 BYTE),
  LAST_MODIFY_TIME     TIMESTAMP(6),
  LAST_MODIFY_ACCOUT   VARCHAR2(128 BYTE),
  DRAW_COMMENT         VARCHAR2(4000 BYTE),
  DRAW_DATE            TIMESTAMP(6),
  CONSTRAINT VILLAGER_WELFARE_DRAW_PK
 PRIMARY KEY
 (ID)
);


CREATE TABLE AUTH_USER
(
  ID              INTEGER                       NOT NULL,
  ACCOUNT         VARCHAR2(128 BYTE)            NOT NULL,
  PASSWORD        VARCHAR2(128 BYTE),
  NAME            VARCHAR2(128 BYTE),
  TELEPHONE       VARCHAR2(128 BYTE),
  SEX             VARCHAR2(128 BYTE),
  PROVINCE        VARCHAR2(128 BYTE),
  CITY            VARCHAR2(128 BYTE),
  DISTRICT        VARCHAR2(128 BYTE),
  DEPARTMENTID    VARCHAR2(128 BYTE),
  DEPARTMENTNAME  VARCHAR2(128 BYTE),
  OFFICE          VARCHAR2(128 BYTE),
  ROLELEVEL       VARCHAR2(128 BYTE),
  PRIMARY KEY
 (ACCOUNT, ID)
);


CREATE TABLE AUTH_DEPARTMENT
(
  DEPARTMENTID    VARCHAR2(128 BYTE)            NOT NULL,
  DEPARTMENTNAME  VARCHAR2(128 BYTE)            NOT NULL,
  CITY            VARCHAR2(128 BYTE),
  DISTRICTNAME    VARCHAR2(128 BYTE),
  COMMENTINFO     VARCHAR2(1024 BYTE)
);


CREATE TABLE AUTH_FUNCTION
(
  FUNCTONID            INTEGER                  NOT NULL,
  FUNCTIONNAME         VARCHAR2(128 BYTE),
  FUNCTIONDISCRIPTION  VARCHAR2(512 BYTE)
);


CREATE TABLE AUTH_GROUP
(
  GROUPID           INTEGER                     NOT NULL,
  GROUPNAME         VARCHAR2(128 BYTE),
  GROUPDISCRIPTION  VARCHAR2(512 BYTE)
);


CREATE TABLE AUTH_GROUP_USER
(
  GROUPID      INTEGER                          NOT NULL,
  GROUPNAME    VARCHAR2(128 BYTE),
  USERACCOUNT  VARCHAR2(128 BYTE),
  USERNAME     VARCHAR2(128 BYTE)
);


CREATE TABLE AUTH_ROLE
(
  ROLEID           INTEGER                      NOT NULL,
  ROLENAME         VARCHAR2(128 BYTE),
  ROLEDISCRIPTION  VARCHAR2(512 BYTE)
);


CREATE TABLE AUTH_ROLE_FUNCTION
(
  ROLEID        INTEGER                         NOT NULL,
  ROLENAME      VARCHAR2(128 BYTE),
  FUNCTIONID    INTEGER,
  FUNCTIONNAME  VARCHAR2(128 BYTE)
);


CREATE TABLE AUTH_USER_ROLE
(
  USERACCOUNT  VARCHAR2(128 BYTE),
  USERID       VARCHAR2(128 BYTE),
  ROLEID       VARCHAR2(128 BYTE),
  ROLENAME     VARCHAR2(128 BYTE)
);


CREATE TABLE LOG_LOGIN
(
  ID                  INTEGER                   NOT NULL,
  USERACCOUNT         VARCHAR2(128 BYTE),
  USERNAME            VARCHAR2(128 BYTE),
  USERDISTRICT        VARCHAR2(128 BYTE),
  USERDEPARTMENTID    VARCHAR2(128 BYTE),
  USERDEPARTMENTNAME  VARCHAR2(128 BYTE),
  TIMESTAMP           TIMESTAMP(6)
);


CREATE TABLE PRODUCT
(
  ID    INTEGER,
  NAME  VARCHAR2(256 BYTE),
  SPEC  VARCHAR2(256 BYTE),
  TYPE  VARCHAR2(256 BYTE)
);


CREATE UNIQUE INDEX ACCOUNT_UNIQUE ON AUTH_USER
(ACCOUNT);




CREATE UNIQUE INDEX VILLAGER_UIDX ON VILLAGER
(ID_CARD);




CREATE INDEX VILLAGER_WELFARE_DRAW_IDX01 ON VILLAGER_WELFARE_DRAW
(VILLAGER_ID);


CREATE UNIQUE INDEX VILLAGER_WELFARE_DRAW_UIDX ON VILLAGER_WELFARE_DRAW
(ID);




CREATE UNIQUE INDEX VILLAGER_WELFARE_UIDX ON VILLAGER_WELFARE
(VILLAGER_ID, WELFARE_POLICY_ID);


CREATE UNIQUE INDEX VILL_WEL_DRAW_DETAIL_UIDX ON VILLAGER_WELFARE_DRAW_DETAIL
(VILLAGER_WELFARE_DRAW_ID, VILLAGER_WELFARE_ID, PRODUCT_ID);




CREATE UNIQUE INDEX WELFARE_POLICY_DETAIL_UIDX ON WELFARE_POLICY_DETAIL
(WELFARE_POLICY_ID, PRODUCT_ID);




